build:
  testing:
    image: webhippie/golang:latest
    commands:
      - make clean
      - make deps
      - make build
      - make test

  release:
    image: webhippie/golang:latest
    commands:
      - make clean
      - make release
    when:
      event: tag

publish:
  coverage:
    server: http://coverage.dronehippie.de
    token: $$GITHUB_APIKEY
    when:
      branch: master

  github_release:
    api_key: $$GITHUB_APIKEY
    files:
      - dist/release/*
    when:
      event: tag

  rsync:
    user: dl
    host: dl.webhippie.de
    source: dist/release/
    target: public_html/solder-cli/$$TAG
    recursive: true
    delete: true
    when:
      event: tag

  rsync:
    user: dl
    host: dl.webhippie.de
    source: dist/latest/
    target: public_html/solder-cli/latest
    recursive: true
    delete: true
    when:
      event: tag

  rsync:
    user: dl
    host: dl.webhippie.de
    source: dist/publish/
    target: public_html/solder-cli/updates
    recursive: true
    delete: false
    when:
      event: tag

notify:
  gitter:
    webhook:
      - $$GITTER_WEBHOOK
    when:
      repo: solderapp/solder-cli

cache:
  mount:
    - vendor
