workspace:
  base: /usr/local
  path: src/github.com/kleister/kleister-cli

pipeline:
  testing:
    image: webhippie/golang:latest
    environment:
      - GOPATH=/usr/local
    commands:
      - make clean
      - make deps
      - make vet
      - make lint
      - make test
      - make build

  updater:
    image: webhippie/golang:latest
    environment:
      - GOPATH=/usr/local
    commands:
      - make release
      - make updater
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  # cover:
  #   image: plugins/coverage

  # rsync:
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-cli/master
  #   recursive: true
  #   delete: true
  #   when:
  #     event: push
  #     branch: master

  # rsync:
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-cli/$$TAG
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag

  # rsync:
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/latest/
  #   target: /usr/share/webapps/dl/public_html/kleister-cli/latest
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag

  # rsync:
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/publish/
  #   target: /usr/share/webapps/dl/public_html/kleister-cli/updates
  #   recursive: true
  #   delete: false
  #   when:
  #     event: tag

  # github_release:
  #   files:
  #     - dist/release/*
  #   when:
  #     event: tag

  docker:
    image: plugins/docker
    storage_driver: overlay
    repo: kleister/kleister-cli
    tags: [ '${TAG}' ]
    when:
      event: tag

  docker:
    image: plugins/docker
    storage_driver: overlay
    repo: kleister/kleister-cli
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

  # gitter:
  #   image: plugins/gitter
