build:
  testing:
    image: webhippie/golang:latest
    commands:
      - make clean
      - make deps
      - make build
      - make test

  release:
    image: webhippie/golang:latest
    commands:
      - make release
    when:
      event: tag

publish:
  coverage:
    server: http://coverage.dronehippie.de
    token: $$GITHUB_APIKEY
    when:
      branch: master

  github_release:
    api_key: $$GITHUB_APIKEY
    files:
      - dist/*
    when:
      event: tag

notify:
  gitter:
    webhook:
      - $$GITTER_WEBHOOK
    when:
      repo: solderapp/solder-cli

cache:
  mount:
    - vendor
