build:
  general:
    image: webhippie/golang:latest
    commands:
      - make clean
      - make build
      - make test
      - make release

  updater:
    image: webhippie/golang:latest
    commands:
      - make updater
    when:
      event: tag

publish:
  coverage:
    server: http://coverage.dronehippie.de
    token: $$GITHUB_APIKEY
    when:
      branch: master

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/release/
    target: $$BASE_PATH/solder-cli/master
    recursive: true
    delete: true
    when:
      branch: master

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/release/
    target: $$BASE_PATH/solder-cli/$$TAG
    recursive: true
    delete: true
    when:
      event: tag

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/latest/
    target: $$BASE_PATH/solder-cli/latest
    recursive: true
    delete: true
    when:
      event: tag

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/publish/
    target: $$BASE_PATH/solder-cli/updates
    recursive: true
    delete: false
    when:
      event: tag

  github_release:
    api_key: $$GITHUB_APIKEY
    files:
      - dist/release/*
    when:
      event: tag

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    storage_driver: overlay
    repo: solderapp/solder-cli
    tag: $$TAG
    when:
      event: tag

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    storage_driver: overlay
    repo: solderapp/solder-cli
    tag: latest
    when:
      branch: master

notify:
  gitter:
    webhook:
      - $$GITTER_WEBHOOK

cache:
  mount:
    - vendor
