[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "3.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/Masterminds/sprig"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/kleister/kleister-go"

[[constraint]]
  name = "gopkg.in/guregu/null.v3"
  version = "3.3.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[prune]
  go-tests = true
  unused-packages = true
