FROM i386/alpine:3.21

RUN apk add --no-cache ca-certificates mailcap && \
    addgroup -g 1337 kleister && \
    adduser -D -u 1337 -h /var/lib/kleister -G kleister kleister

ENTRYPOINT ["/usr/bin/kleister-cli"]
CMD ["help"]

COPY bin/kleister-cli /usr/bin/kleister-cli
WORKDIR /var/lib/kleister
USER kleister
